In [87]:
#importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [88]:
#Load data
df = pd.read_excel(r'C:\Users\Dhruv Kumar Jha\Downloads\Graphene AI\Unsupervised-Text-Clustering using NLP\Clusters-dataset.xlsx')
df

                             string  cluster_id
0                salary good bonus            1
1       employees are treated well            2
2    flexibility to work from home            3
3    employee friendly environment            4
4            good benefits pension            5
..                              ...         ...
146      high growth opportunities           13
147                culture is good           14
148         associates feel valued           18
149             number one company           22
150                  company value           27

[151 rows x 2 columns]

In [89]:
from collections import Counter
import nltk

In [8]:
# The POS tagger in the NLTK library outputs specific tags for certain words. The list of POS tags is as follows, with examples of what each POS stands for.

# CC coordinating conjunction
# CD cardinal digit
# DT determiner
# EX existential there (like: “there is” … think of it like “there exists”)
# FW foreign word
# IN preposition/subordinating conjunction
# JJ adjective ‘big’
# JJR adjective, comparative ‘bigger’
# JJS adjective, superlative ‘biggest’
# LS list marker 1)
# MD modal could, will
# NN noun, singular ‘desk’
# NNS noun plural ‘desks’
# NNP proper noun, singular ‘Harrison’
# NNPS proper noun, plural ‘Americans’
# PDT predeterminer ‘all the kids’
# POS possessive ending parent’s
# PRP personal pronoun I, he, she
# PRP$ possessive pronoun my, his, hers
# RB adverb very, silently,
# RBR adverb, comparative better
# RBS adverb, superlative best
# RP particle give up
# TO, to go ‘to’ the store.
# UH interjection, errrrrrrrm
# VB verb, base form take
# VBD verb, past tense took
# VBG verb, gerund/present participle taking
# VBN verb, past participle taken
# VBP verb, sing. present, non-3d take
# VBZ verb, 3rd person sing. present takes
# WDT wh-determiner which
# WP wh-pronoun who, what
# WP$ possessive wh-pronoun whose
# WRB wh-abverb where, when

In [99]:
X = []
Y = []

for i in df['string']:
    text = i
    lower_case = text.lower()
    tokens = nltk.word_tokenize(lower_case)
    tags = nltk.pos_tag(tokens)
    counts = Counter( tag for word,  tag in tags)
    
    #count the adjectives
    JJ_count = 0
    #count the nouns
    NN_count = 0
    
    for pair in tags:
        tag = pair[1]
        if tag == 'JJ':
            JJ_count += 1
        if tag == 'NN':
            NN_count += 1
    X.append(NN_count)
    Y.append(JJ_count)
    print(tags)

[('salary', 'JJ'), ('good', 'JJ'), ('bonus', 'NN')]
[('employees', 'NNS'), ('are', 'VBP'), ('treated', 'VBN'), ('well', 'RB')]
[('flexibility', 'NN'), ('to', 'TO'), ('work', 'VB'), ('from', 'IN'), ('home', 'NN')]
[('employee', 'NN'), ('friendly', 'JJ'), ('environment', 'NN')]
[('good', 'JJ'), ('benefits', 'NNS'), ('pension', 'NN')]
[('leaders', 'NNS'), ('are', 'VBP'), ('great', 'JJ')]
[('facilities', 'NNS'), ('is', 'VBZ'), ('good', 'JJ')]
[('hr', 'NN'), ('working', 'NN'), ('is', 'VBZ'), ('good', 'JJ')]
[('team', 'NN'), ('were', 'VBD'), ('great', 'JJ')]
[('free', 'JJ'), ('food', 'NN')]
[('good', 'JJ'), ('opportunity', 'NN'), ('for', 'IN'), ('freshers', 'NNS')]
[('creative', 'JJ'), ('place', 'NN'), ('to', 'TO'), ('work', 'VB')]
[('good', 'JJ'), ('place', 'NN'), ('to', 'TO'), ('learn', 'VB')]
[('good', 'JJ'), ('work', 'NN'), ('environment', 'NN')]
[('good', 'JJ'), ('work', 'NN'), ('life', 'NN'), ('balance', 'NN')]
[('location', 'NN'), ('is', 'VBZ'), ('convenient', 'JJ')]
[('stable', 'JJ'), ('job', 'NN')]
[('excellent', 'JJ'), ('training', 'NN'), ('employees', 'NNS')]
[('innovative', 'JJ'), ('products', 'NNS')]
[('[', 'NN'), ('best', 'JJS'), ('for', 'IN'), ('the', 'DT'), ('customers', 'NNS')]
[('good', 'JJ'), ('training', 'NN'), ('program', 'NN')]
[('enjoyed', 'VBN'), ('the', 'DT'), ('job', 'NN'), ('a', 'DT'), ('lot', 'NN')]
[('company', 'NN'), ('is', 'VBZ'), ('fast', 'RB'), ('growing', 'VBG')]
[('good', 'JJ'), ('salary', 'JJ'), ('pay', 'NN')]
[('leader', 'NN'), ('in', 'IN'), ('industry', 'NN')]
[('people', 'NNS'), ('around', 'IN'), ('encouraging', 'VBG')]
[('company', 'NN'), ('upholds', 'VBZ'), ('great', 'JJ'), ('values', 'NNS')]
[('strong', 'JJ'), ('company', 'NN'), ('financially', 'RB')]
[('[', 'NN'), ('go', 'VB'), ('into', 'IN'), ('work', 'NN'), ('excited', 'VBD')]
[('support', 'NN'), ('from', 'IN'), ('seniors', 'NNS'), ('are', 'VBP'), ('good', 'JJ')]
[('management', 'NN'), ('accommodates', 'NNS'), ('for', 'IN'), ('disabilities', 'NNS')]
[('job', 'NN'), ('fast', 'RB'), ('paced', 'VBD')]
[('[', 'NN'), ('satisfied', 'VBD'), ('in', 'IN'), ('job', 'NN')]
[('staff', 'NN'), ('are', 'VBP'), ('helpful', 'JJ')]
[('very', 'RB'), ('lgbtq', 'RB'), ('friendly', 'JJ')]
[('management', 'NN'), ('empowers', 'NNS'), ('employees', 'NNS')]
[('good', 'JJ'), ('salary', 'NN'), ('and', 'CC'), ('incentives', 'NNS')]
[('employees', 'NNS'), ('respected', 'VBD'), ('very', 'RB'), ('much', 'JJ')]
[('schedule', 'NN'), ('is', 'VBZ'), ('flexible', 'JJ')]
[('environment', 'NN'), ('is', 'VBZ'), ('very', 'RB'), ('friendly', 'JJ')]
[('good', 'JJ'), ('compensation', 'NN'), ('health', 'NN'), ('care', 'NN')]
[('ceo', 'NN'), ('is', 'VBZ'), ('great', 'JJ')]
[('nice', 'RB'), ('canteen', 'NN'), ('facilities', 'NNS')]
[('hr', 'NN'), ('policies', 'NNS'), ('are', 'VBP'), ('good', 'JJ')]
[('great', 'JJ'), ('ppl', 'NN'), ('to', 'TO'), ('work', 'VB'), ('with', 'IN')]
[('cafeteria', 'NNS'), ('are', 'VBP'), ('great', 'JJ')]
[('good', 'JJ'), ('company', 'NN'), ('for', 'IN'), ('fresher', 'NN')]
[('company', 'NN'), ('attracts', 'VBZ'), ('creative', 'JJ')]
[('good', 'JJ'), ('opportunity', 'NN'), ('to', 'TO'), ('learn', 'VB')]
[('good', 'JJ'), ('work', 'NN'), ('culture', 'NN')]
[('hours', 'NNS'), ('was', 'VBD'), ('good', 'JJ')]
[('great', 'JJ'), ('location', 'NN')]
[('job', 'NN'), ('security', 'NN'), ('for', 'IN'), ('me', 'PRP')]
[('value', 'NN'), ('their', 'PRP$'), ('employees', 'NNS')]
[('company', 'NN'), ('is', 'VBZ'), ('innovative', 'JJ')]
[('keeping', 'VBG'), ('customers', 'NNS'), ('happy', 'JJ')]
[('good', 'JJ'), ('training', 'NN'), ('opportunities', 'NNS')]
[('loved', 'VBN'), ('working', 'VBG'), ('with', 'IN'), ('company', 'NN')]
[('growing', 'VBG'), ('company', 'NN'), ('with', 'IN'), ('great', 'JJ'), ('pay', 'NN')]
[('respectful', 'JJ'), ('work', 'NN'), ('environment', 'NN')]
[('adopts', 'NNS'), ('latest', 'JJS'), ('technology', 'NN')]
[('very', 'RB'), ('encouraging', 'JJ'), ('environment', 'NN')]
[('has', 'VBZ'), ('great', 'JJ'), ('values', 'NNS')]
[('stable', 'JJ'), ('company', 'NN')]
[('workplace', 'NN'), ('was', 'VBD'), ('enthusiastic', 'JJ')]
[('bosses', 'NNS'), ('were', 'VBD'), ('always', 'RB'), ('motivating', 'VBG')]
[('very', 'RB'), ('inclusive', 'JJ'), ('culture', 'NN')]
[('fast', 'RB'), ('paced', 'VBD')]
[('satisfaction', 'NN'), ('for', 'IN'), ('job', 'NN')]
[('managers', 'NNS'), ('treated', 'VBD'), ('me', 'PRP'), ('well', 'RB')]
[('employees', 'NNS'), ('were', 'VBD'), ('respectful', 'JJ')]
[('employees', 'NNS'), ('are', 'VBP'), ('empowered', 'VBN')]
[('good', 'JJ'), ('salary', 'NN'), ('incentives', 'NNS')]
[('managers', 'NNS'), ('were', 'VBD'), ('respectful', 'JJ')]
[('flexible', 'JJ'), ('hours', 'NNS'), ('with', 'IN'), ('school', 'NN')]
[('culture', 'NN'), ('is', 'VBZ'), ('employment', 'NN'), ('friendly', 'RB')]
[('benefits', 'NNS'), ('are', 'VBP'), ('good', 'JJ')]
[('enjoyed', 'VBN'), ('working', 'VBG'), ('with', 'IN'), ('company', 'NN')]
[('infrastructure', 'NN'), ('is', 'VBZ'), ('good', 'JJ')]
[('good', 'JJ'), ('hr', 'NN'), ('support', 'NN')]
[('colleagues', 'NNS'), ('are', 'VBP'), ('helpful', 'JJ')]
[('food', 'NN'), ('is', 'VBZ'), ('great', 'JJ'), ('quality', 'NN')]
[('good', 'JJ'), ('to', 'TO'), ('start', 'VB'), ('your', 'PRP$'), ('career', 'NN')]
[('lots', 'NNS'), ('creative', 'VBP'), ('freedom', 'NN')]
[('good', 'JJ'), ('learning', 'NN'), ('programs', 'NNS')]
[('good', 'JJ'), ('place', 'NN'), ('to', 'TO'), ('work', 'VB')]
[('very', 'RB'), ('good', 'JJ'), ('organization', 'NN')]
[('good', 'JJ'), ('working', 'NN'), ('location', 'NN')]
[('job', 'NN'), ('security', 'NN'), ('excellent', 'NN')]
[('employees', 'NNS'), ('truly', 'RB'), ('felt', 'VBD'), ('valued', 'VBN')]
[('enjoying', 'VBG'), ('work', 'NN')]
[('loved', 'VBN'), ('working', 'VBG'), ('with', 'IN'), ('the', 'DT'), ('customers', 'NNS')]
[('training', 'NN'), ('is', 'VBZ'), ('excellent', 'JJ')]
[('enjoyed', 'VBN'), ('working', 'VBG'), ('torrent', 'NN')]
[('top', 'JJ'), ('growing', 'VBG'), ('company', 'NN')]
[('loved', 'VBN'), ('company', 'NN')]
[('company', 'NN'), ('is', 'VBZ'), ('motivating', 'VBG')]
[('company', 'NN'), ('with', 'IN'), ('great', 'JJ'), ('values', 'NNS')]
[('job', 'NN'), ('was', 'VBD'), ('exciting', 'VBG')]
[('management', 'NN'), ('is', 'VBZ'), ('very', 'RB'), ('supportive', 'JJ')]
[('inclusive', 'JJ'), ('environment', 'NN')]
[('love', 'VB'), ('product', 'NN'), ('fast', 'RB'), ('paced', 'VBD'), ('well', 'RB')]
[('treated', 'VBN'), ('like', 'IN'), ('family', 'NN')]
[('good', 'JJ'), ('company', 'NN'), ('for', 'IN'), ('work', 'NN')]
[('empowered', 'VBN'), ('to', 'TO'), ('make', 'VB'), ('decisions', 'NNS')]
[('good', 'JJ'), ('bonuses', 'NNS')]
[('coworkers', 'NNS'), ('were', 'VBD'), ('very', 'RB'), ('respectful', 'JJ')]
[('good', 'JJ'), ('flexible', 'JJ'), ('hours', 'NNS')]
[('very', 'RB'), ('friendly', 'JJ'), ('colleagues', 'NNS')]
[('good', 'JJ'), ('vacation', 'NN'), ('time', 'NN')]
[('good', 'JJ'), ('employee', 'NN'), ('facility', 'NN')]
[('best', 'JJS'), ('hr', 'NN'), ('policy', 'NN')]
[('colleagues', 'NNS'), ('are', 'VBP'), ('supportive', 'JJ')]
[('free', 'JJ'), ('snacks', 'NNS'), ('provide', 'VBP')]
[('good', 'JJ'), ('company', 'NN'), ('to', 'TO'), ('start', 'VB'), ('career', 'NN')]
[('great', 'JJ'), ('creative', 'JJ'), ('environment', 'NN')]
[('excellent', 'JJ'), ('learning', 'VBG'), ('platform', 'NN')]
[('good', 'JJ'), ('atmosphere', 'NN'), ('to', 'TO'), ('work', 'VB')]
[('location', 'NN'), ('is', 'VBZ'), ('great', 'JJ')]
[('job', 'NN'), ('is', 'VBZ'), ('secure', 'JJ')]
[('great', 'JJ'), ('employee', 'NN'), ('company', 'NN'), ('values', 'NNS')]
[('satisfaction', 'NN'), ('the', 'DT'), ('customers', 'NNS')]
[('very', 'RB'), ('happy', 'JJ')]
[('very', 'RB'), ('ethical', 'JJ'), ('company', 'NN')]
[('management', 'NN'), ('are', 'VBP'), ('good', 'JJ')]
[('company', 'NN'), ('is', 'VBZ'), ('very', 'RB'), ('inclusive', 'JJ')]
[('really', 'RB'), ('fast', 'JJ'), ('pace', 'NN')]
[('incentive', 'NN'), ('is', 'VBZ'), ('good', 'JJ')]
[('people', 'NNS'), ('was', 'VBD'), ('respectful', 'JJ')]
[('friendly', 'JJ'), ('work', 'NN'), ('environment', 'NN')]
[('good', 'JJ'), ('health', 'NN'), ('benefits', 'NNS')]
[('very', 'RB'), ('supportive', 'JJ'), ('team', 'NN'), ('members', 'NNS')]
[('good', 'JJ'), ('lunch', 'NN'), ('breaks', 'NNS')]
[('good', 'JJ'), ('environment', 'NN'), ('for', 'IN'), ('the', 'DT'), ('freshers', 'NNS')]
[('has', 'VBZ'), ('many', 'JJ'), ('opportunities', 'NNS'), ('for', 'IN'), ('advancement', 'NN')]
[('inclusive', 'JJ'), ('work', 'NN'), ('culture', 'NN')]
[('felt', 'NN'), ('valued', 'VBN'), ('by', 'IN'), ('coworkers', 'NNS')]
[('was', 'VBD'), ('a', 'DT'), ('great', 'JJ'), ('experience', 'NN')]
[('company', 'NN'), ('pushes', 'VBZ'), ('integrity', 'NN')]
[('upper', 'JJ'), ('management', 'NN'), ('was', 'VBD'), ('great', 'JJ')]
[('fast', 'RB'), ('paced', 'VBN'), ('store', 'NN')]
[('treated', 'VBN'), ('me', 'PRP'), ('very', 'RB'), ('well', 'RB')]
[('good', 'JJ'), ('co', 'NN'), ('workers', 'NNS')]
[('company', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('good', 'JJ')]
[('values', 'NNS'), ('are', 'VBP'), ('great', 'JJ')]
[('good', 'JJ'), ('for', 'IN'), ('fresher', 'NN')]
[('high', 'JJ'), ('growth', 'NN'), ('opportunities', 'NNS')]
[('culture', 'NN'), ('is', 'VBZ'), ('good', 'JJ')]
[('associates', 'NNS'), ('feel', 'VBP'), ('valued', 'VBN')]
[('number', 'NN'), ('one', 'CD'), ('company', 'NN')]
[('company', 'NN'), ('value', 'NN')]

In [100]:
df['NN'] = X
df['JJ'] = Y

df

                             string  cluster_id  NN  JJ
0                salary good bonus            1   1   2
1       employees are treated well            2   0   0
2    flexibility to work from home            3   2   0
3    employee friendly environment            4   2   1
4            good benefits pension            5   1   1
..                              ...         ...  ..  ..
146      high growth opportunities           13   1   1
147                culture is good           14   1   1
148         associates feel valued           18   0   0
149             number one company           22   2   0
150                  company value           27   2   0

[151 rows x 4 columns]

In [101]:
df.shape

(151, 4)

In [102]:
# Create document-term matrix
from sklearn.feature_extraction import text 
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
data_cv = cv.fit_transform(df.string)

In [103]:
data_stop = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_stop.index = df.index

C:\Users\Dhruv Kumar Jha\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [104]:
# Pickle it for later use
import pickle
pickle.dump(cv, open("cv_stop.pkl", "wb"))
data_stop.to_pickle("dtm_stop.pkl")

In [105]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,accommodates,adopts,advancement,always,and,are,around,associates,atmosphere,attracts,...,very,was,well,were,with,work,workers,working,workplace,your
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
148,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [106]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

In [107]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,150
accommodates,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
adopts,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
advancement,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
always,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
and,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [108]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [109]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

In [110]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.112*"good" + 0.060*"company" + 0.038*"is" + 0.029*"for" + 0.024*"job" + 0.023*"work" + 0.022*"very" + 0.016*"working" + 0.015*"the" + 0.014*"culture"'),
 (1,
  '0.055*"great" + 0.039*"are" + 0.027*"environment" + 0.024*"employees" + 0.022*"to" + 0.022*"is" + 0.021*"very" + 0.021*"work" + 0.020*"friendly" + 0.020*"was"')]

In [111]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.077*"good" + 0.075*"is" + 0.062*"great" + 0.051*"company" + 0.023*"was" + 0.020*"values" + 0.019*"fast" + 0.016*"working" + 0.016*"location" + 0.016*"creative"'),
 (1,
  '0.082*"good" + 0.034*"are" + 0.033*"to" + 0.023*"employees" + 0.022*"excellent" + 0.022*"treated" + 0.017*"valued" + 0.017*"hours" + 0.017*"benefits" + 0.017*"well"'),
 (2,
  '0.048*"very" + 0.040*"environment" + 0.038*"work" + 0.038*"good" + 0.038*"company" + 0.036*"job" + 0.028*"for" + 0.027*"are" + 0.024*"the" + 0.023*"culture"')]

In [112]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.100*"good" + 0.075*"work" + 0.067*"are" + 0.045*"to" + 0.037*"great" + 0.028*"culture" + 0.021*"salary" + 0.018*"well" + 0.018*"place" + 0.018*"location"'),
 (1,
  '0.055*"were" + 0.053*"respectful" + 0.048*"fast" + 0.046*"company" + 0.042*"paced" + 0.024*"employees" + 0.024*"value" + 0.024*"free" + 0.016*"growing" + 0.014*"stable"'),
 (2,
  '0.067*"good" + 0.066*"company" + 0.065*"is" + 0.040*"very" + 0.038*"great" + 0.036*"job" + 0.032*"environment" + 0.025*"with" + 0.024*"friendly" + 0.021*"working"'),
 (3,
  '0.061*"good" + 0.036*"for" + 0.028*"customers" + 0.027*"the" + 0.027*"is" + 0.022*"was" + 0.022*"management" + 0.022*"benefits" + 0.022*"very" + 0.021*"flexible"')]

### Topic Modeling - Attempt #2 (Nouns Only)

In [113]:
from nltk.corpus import stopwords
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger') 
import string
from nltk import word_tokenize, pos_tag

[nltk_data] Downloading package punkt to C:\Users\Dhruv Kumar
[nltk_data]     Jha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Dhruv Kumar Jha\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [114]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [115]:
data_nouns = pd.DataFrame(df.string.apply(nouns))
data_nouns

                   string
0                   bonus
1               employees
2        flexibility home
3    employee environment
4        benefits pension
..                    ...
146  growth opportunities
147               culture
148            associates
149        number company
150         company value

[151 rows x 1 columns]

In [116]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer


# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)


# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.string)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

C:\Users\Dhruv Kumar Jha\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,accommodates,adopts,advancement,associates,atmosphere,balance,benefits,bonus,bonuses,bosses,...,technology,torrent,training,vacation,value,values,work,workers,working,workplace
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
148,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [117]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [118]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.136*"company" + 0.054*"job" + 0.054*"work" + 0.051*"environment" + 0.032*"values" + 0.032*"management" + 0.031*"culture" + 0.020*"employee" + 0.020*"place" + 0.020*"hours"'),
 (1,
  '0.062*"employees" + 0.033*"training" + 0.033*"location" + 0.033*"customers" + 0.026*"benefits" + 0.025*"opportunities" + 0.021*"hr" + 0.018*"working" + 0.018*"facilities" + 0.018*"food"')]

In [119]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.142*"company" + 0.077*"job" + 0.077*"work" + 0.076*"environment" + 0.044*"culture" + 0.035*"hr" + 0.028*"place" + 0.026*"employee" + 0.019*"fresher" + 0.019*"security"'),
 (1,
  '0.069*"company" + 0.057*"values" + 0.046*"location" + 0.045*"training" + 0.035*"colleagues" + 0.026*"benefits" + 0.025*"hours" + 0.025*"health" + 0.025*"food" + 0.025*"pay"'),
 (2,
  '0.090*"employees" + 0.058*"management" + 0.047*"customers" + 0.025*"salary" + 0.025*"facilities" + 0.025*"incentives" + 0.025*"opportunity" + 0.025*"team" + 0.023*"freshers" + 0.015*"opportunities"')]

In [120]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.137*"job" + 0.064*"training" + 0.059*"hr" + 0.049*"place" + 0.034*"working" + 0.034*"food" + 0.034*"managers" + 0.033*"pay" + 0.033*"satisfaction" + 0.019*"opportunities"'),
 (1,
  '0.065*"customers" + 0.050*"benefits" + 0.035*"facilities" + 0.035*"coworkers" + 0.030*"support" + 0.020*"opportunities" + 0.019*"health" + 0.019*"balance" + 0.019*"life" + 0.019*"industry"'),
 (2,
  '0.125*"environment" + 0.071*"work" + 0.044*"location" + 0.044*"hours" + 0.044*"colleagues" + 0.030*"incentives" + 0.030*"freshers" + 0.030*"salary" + 0.030*"team" + 0.022*"management"'),
 (3,
  '0.229*"company" + 0.080*"employees" + 0.052*"culture" + 0.052*"values" + 0.038*"management" + 0.032*"employee" + 0.032*"work" + 0.022*"career" + 0.022*"value" + 0.022*"security"')]

### Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [121]:
from nltk.corpus import stopwords
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger') 
import string
from nltk import word_tokenize, pos_tag

[nltk_data] Downloading package punkt to C:\Users\Dhruv Kumar
[nltk_data]     Jha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Dhruv Kumar Jha\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [122]:
# Let's create a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [123]:
data_nouns_adj = pd.DataFrame(df.string.apply(nouns_adj))
data_nouns_adj

                            string
0                salary good bonus
1                        employees
2                 flexibility home
3    employee friendly environment
4            good benefits pension
..                             ...
146      high growth opportunities
147                   culture good
148                     associates
149                 number company
150                  company value

[151 rows x 1 columns]

In [124]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(max_df=.8) #, max_df is used for removing data values that appear too frequently, also known as "corpus-specific stop words". 
# For example, max_df=.8 means "It ignores terms that appear in more than 80% of the documents". 
data_cvna = cvna.fit_transform(data_nouns_adj.string)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

C:\Users\Dhruv Kumar Jha\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,accommodates,adopts,advancement,associates,atmosphere,balance,benefits,best,bonus,bonuses,...,torrent,training,upper,vacation,value,values,work,workers,working,workplace
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
148,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [125]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [126]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.159*"good" + 0.084*"company" + 0.035*"work" + 0.032*"employees" + 0.030*"job" + 0.019*"culture" + 0.017*"salary" + 0.017*"excellent" + 0.016*"location" + 0.013*"hours"'),
 (1,
  '0.085*"great" + 0.038*"environment" + 0.028*"friendly" + 0.028*"values" + 0.023*"customers" + 0.023*"respectful" + 0.021*"inclusive" + 0.020*"management" + 0.018*"colleagues" + 0.017*"opportunities"')]

In [127]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.258*"good" + 0.028*"salary" + 0.022*"benefits" + 0.022*"place" + 0.017*"job" + 0.015*"hours" + 0.015*"health" + 0.015*"incentives" + 0.015*"opportunity" + 0.015*"facilities"'),
 (1,
  '0.113*"great" + 0.054*"employees" + 0.047*"company" + 0.046*"job" + 0.035*"management" + 0.035*"values" + 0.028*"excellent" + 0.028*"inclusive" + 0.025*"training" + 0.022*"colleagues"'),
 (2,
  '0.106*"company" + 0.062*"work" + 0.060*"environment" + 0.036*"respectful" + 0.035*"friendly" + 0.033*"good" + 0.029*"customers" + 0.029*"hr" + 0.025*"culture" + 0.016*"innovative"')]

In [128]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.087*"good" + 0.082*"work" + 0.053*"culture" + 0.046*"environment" + 0.042*"management" + 0.033*"respectful" + 0.032*"creative" + 0.029*"inclusive" + 0.023*"opportunities" + 0.022*"freshers"'),
 (1,
  '0.180*"company" + 0.089*"great" + 0.042*"friendly" + 0.041*"values" + 0.039*"environment" + 0.026*"colleagues" + 0.026*"supportive" + 0.026*"employee" + 0.024*"good" + 0.018*"career"'),
 (2,
  '0.221*"good" + 0.038*"great" + 0.029*"location" + 0.029*"salary" + 0.029*"hr" + 0.021*"benefits" + 0.015*"place" + 0.015*"health" + 0.015*"support" + 0.015*"free"'),
 (3,
  '0.107*"job" + 0.098*"employees" + 0.051*"customers" + 0.046*"excellent" + 0.027*"training" + 0.027*"satisfaction" + 0.027*"people" + 0.027*"happy" + 0.027*"respectful" + 0.015*"flexible"')]

### Identify Topics in Each Document

In [129]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.102*"good" + 0.052*"company" + 0.042*"salary" + 0.033*"management" + 0.032*"supportive" + 0.032*"place" + 0.032*"creative" + 0.023*"colleagues" + 0.022*"incentives" + 0.022*"innovative"'),
 (1,
  '0.141*"great" + 0.141*"good" + 0.043*"values" + 0.027*"location" + 0.027*"benefits" + 0.027*"employee" + 0.027*"company" + 0.023*"friendly" + 0.018*"opportunities" + 0.018*"opportunity"'),
 (2,
  '0.084*"employees" + 0.066*"good" + 0.043*"hr" + 0.043*"excellent" + 0.034*"respectful" + 0.033*"flexible" + 0.033*"hours" + 0.023*"customers" + 0.023*"training" + 0.023*"best"'),
 (3,
  '0.114*"company" + 0.082*"good" + 0.069*"work" + 0.069*"environment" + 0.069*"job" + 0.039*"culture" + 0.032*"inclusive" + 0.020*"friendly" + 0.017*"stable" + 0.017*"satisfaction"')]

In [130]:
# topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=80)
ldan.print_topics()

[(0,
  '0.054*"hr" + 0.054*"customers" + 0.041*"hours" + 0.041*"benefits" + 0.029*"support" + 0.029*"team" + 0.029*"facilities" + 0.029*"opportunity" + 0.029*"pay" + 0.029*"working"'),
 (1,
  '0.192*"company" + 0.077*"job" + 0.053*"environment" + 0.044*"values" + 0.036*"training" + 0.027*"employee" + 0.027*"colleagues" + 0.019*"opportunities" + 0.019*"security" + 0.019*"career"'),
 (2,
  '0.089*"work" + 0.079*"employees" + 0.051*"culture" + 0.051*"management" + 0.041*"location" + 0.032*"place" + 0.031*"environment" + 0.022*"incentives" + 0.022*"salary" + 0.022*"food"')]